#!/usr/bin/env bash
#
# Install the Cloudflare Tunnel for Shrimp Cam as a system service.
#
# Why this script exists: `sudo cloudflared service install` runs as root, so it
# looks for its config in /root/.cloudflared and /etc/cloudflared — NOT in your
# own home directory. Putting config.yml in ~/.cloudflared therefore fails with:
#
#   Cannot determine default configuration path. No file [config.yml config.yaml]
#
# This script writes the config (and the tunnel credentials) into
# /etc/cloudflared, where the root-run service can actually read them.
#
# Prerequisites:
#   cloudflared tunnel login
#   cloudflared tunnel create shrimpcam
#   cloudflared tunnel route dns shrimpcam <your-hostname>
#
# Usage:
#   TUNNEL_HOSTNAME=shrimp.example.com bash install-tunnel.sh
#   TUNNEL_HOSTNAME=shrimp.example.com TUNNEL_NAME=mycam PORT=8080 bash install-tunnel.sh
#
set -euo pipefail

TUNNEL_NAME="${TUNNEL_NAME:-shrimpcam}"
LOCAL_PORT="${PORT:-8080}"
CONF_DIR="/etc/cloudflared"

# NOTE: deliberately not called HOSTNAME — bash sets that to the machine name.
if [[ -z "${TUNNEL_HOSTNAME:-}" ]]; then
  echo "Set TUNNEL_HOSTNAME to the public hostname you routed to this tunnel." >&2
  echo "  e.g. TUNNEL_HOSTNAME=shrimp.example.com bash install-tunnel.sh" >&2
  exit 1
fi

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "cloudflared is not installed or not on PATH. See the README." >&2
  exit 1
fi

# When run under sudo, look in the invoking user's home for the credentials the
# `cloudflared tunnel create` step wrote.
RUN_USER="${SUDO_USER:-$(id -un)}"
USER_HOME="$(getent passwd "${RUN_USER}" | cut -d: -f6)"
: "${USER_HOME:=${HOME}}"

# Resolve the tunnel UUID from its name unless the caller supplied one.
if [[ -z "${TUNNEL_ID:-}" ]]; then
  TUNNEL_ID="$(cloudflared tunnel list 2>/dev/null \
    | awk -v n="${TUNNEL_NAME}" '$2 == n { print $1; exit }')"
fi

if [[ -z "${TUNNEL_ID:-}" ]]; then
  echo "Could not find a tunnel named '${TUNNEL_NAME}'." >&2
  echo "Create one first:  cloudflared tunnel create ${TUNNEL_NAME}" >&2
  echo "Or pass an explicit TUNNEL_ID=<uuid>." >&2
  exit 1
fi

CREDS="${USER_HOME}/.cloudflared/${TUNNEL_ID}.json"
if [[ ! -f "${CREDS}" ]]; then
  echo "Tunnel credentials not found at ${CREDS}" >&2
  echo "Re-run:  cloudflared tunnel create ${TUNNEL_NAME}" >&2
  exit 1
fi

echo "Configuring Cloudflare Tunnel"
echo "  tunnel:    ${TUNNEL_NAME} (${TUNNEL_ID})"
echo "  hostname:  ${TUNNEL_HOSTNAME}"
echo "  local app: http://localhost:${LOCAL_PORT}"

sudo mkdir -p "${CONF_DIR}"

# The credentials file is a secret — root-only.
sudo install -m 600 "${CREDS}" "${CONF_DIR}/${TUNNEL_ID}.json"

tmp="$(mktemp)"
trap 'rm -f "${tmp}"' EXIT
cat > "${tmp}" <<EOF
# Generated by install-tunnel.sh — edit and re-run \`sudo systemctl restart cloudflared\`.
tunnel: ${TUNNEL_ID}
credentials-file: ${CONF_DIR}/${TUNNEL_ID}.json

ingress:
  - hostname: ${TUNNEL_HOSTNAME}
    service: http://localhost:${LOCAL_PORT}
  # Required catch-all: anything else returns 404.
  - service: http_status:404
EOF
sudo install -m 644 "${tmp}" "${CONF_DIR}/config.yml"

# Catch typos before we hand the config to systemd.
echo
echo "Validating ingress rules..."
sudo cloudflared --config "${CONF_DIR}/config.yml" tunnel ingress validate

# `service install` refuses to overwrite an existing unit, so replace cleanly.
if systemctl list-unit-files 2>/dev/null | grep -q '^cloudflared\.service'; then
  echo "Existing cloudflared service found — reinstalling."
  sudo cloudflared service uninstall >/dev/null 2>&1 || true
fi

sudo cloudflared service install
sudo systemctl enable --now cloudflared

echo
sudo systemctl status cloudflared --no-pager || true
echo
echo "Logs:  journalctl -u cloudflared -f"
echo "Open:  https://${TUNNEL_HOSTNAME}"
echo
echo "Next: lock it down with Cloudflare Access (Zero Trust -> Access ->"
echo "Applications) so only you can reach the camera. See the README."
